name: Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Initialize Terraform
        run: docker run -v $(pwd):/app paranthaman2k/aws-terraform:V1 terraform init
      - name: Plan Terraform changes
        run: docker run -v $(pwd):/app paranthaman2k/aws-terraform:V1 terraform plan
